In [ ]:
from sklearn import linear_model

reg = linear_model.LinearRegression()
reg.fit([[0, 0], [1, 1], [2, 2]], [0, 1, 2])



,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [4]:
reg.coef_

array([0.5, 0.5])

In [5]:
reg.intercept_

4.440892098500626e-16

In [ ]:
from sklearn.datasets import load_iris

dataset = load_iris()


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [12]:
import pandas as pd

df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df['target'] = dataset.target

In [14]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [17]:
df.shape

(150, 5)

In [18]:
X= df.drop('target',axis= 1)
y = df['target']

In [19]:
X.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [20]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y ,test_size= 0.2,random_state= 2,shuffle=True)

In [22]:
X_train

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
126,6.2,2.8,4.8,1.8
23,5.1,3.3,1.7,0.5
64,5.6,2.9,3.6,1.3
117,7.7,3.8,6.7,2.2
84,5.4,3.0,4.5,1.5
...,...,...,...,...
75,6.6,3.0,4.4,1.4
43,5.0,3.5,1.6,0.6
22,4.6,3.6,1.0,0.2
72,6.3,2.5,4.9,1.5


In [23]:
X_test

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
6,4.6,3.4,1.4,0.3
3,4.6,3.1,1.5,0.2
113,5.7,2.5,5.0,2.0
12,4.8,3.0,1.4,0.1
24,4.8,3.4,1.9,0.2
129,7.2,3.0,5.8,1.6
25,5.0,3.0,1.6,0.2
108,6.7,2.5,5.8,1.8
128,6.4,2.8,5.6,2.1
45,4.8,3.0,1.4,0.3


In [24]:
y_train

126    2
23     0
64     1
117    2
84     1
      ..
75     1
43     0
22     0
72     1
15     0
Name: target, Length: 120, dtype: int64

In [25]:
y_test

6      0
3      0
113    2
12     0
24     0
129    2
25     0
108    2
128    2
45     0
48     0
42     0
35     0
5      0
85     1
54     1
41     0
96     1
144    2
89     1
77     1
74     1
115    2
94     1
87     1
29     0
2      0
127    2
44     0
125    2
Name: target, dtype: int64

In [26]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [29]:
model.predict(X_test)

array([ 5.32612011e-02,  2.42041149e-02,  1.82847351e+00, -7.76592795e-02,
        6.69375598e-02,  1.53849164e+00,  6.96409099e-03,  1.75110748e+00,
        1.92364442e+00,  5.38081344e-02, -8.39026413e-02, -1.86599785e-04,
       -8.47318808e-02,  6.61809695e-02,  1.38297598e+00,  1.31677887e+00,
        1.04327932e-01,  1.18494562e+00,  2.14706156e+00,  1.18806016e+00,
        1.49648078e+00,  1.13001864e+00,  1.97258723e+00,  1.20667636e+00,
        1.19392705e+00,  2.81478955e-02, -3.23725066e-02,  1.60641283e+00,
        1.44214862e-01,  1.69930388e+00])

In [31]:
import numpy as np 

y_pred  = model.predict(X_test)
y_pred_rounded = np.round(y_pred)
y_pred_rounded

array([ 0.,  0.,  2., -0.,  0.,  2.,  0.,  2.,  2.,  0., -0., -0., -0.,
        0.,  1.,  1.,  0.,  1.,  2.,  1.,  1.,  1.,  2.,  1.,  1.,  0.,
       -0.,  2.,  0.,  2.])

In [32]:
y_pred_rounded[:10]

array([ 0.,  0.,  2., -0.,  0.,  2.,  0.,  2.,  2.,  0.])

In [35]:
y_test[:10]

6      0
3      0
113    2
12     0
24     0
129    2
25     0
108    2
128    2
45     0
Name: target, dtype: int64

In [41]:
from sklearn.linear_model import LogisticRegression

model_log = LogisticRegression()
model_log.fit(X_train,y_train)

y_pred_log=model_log.predict(X_test)
y_pred_log

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 1,
       2, 1, 1, 0, 0, 2, 0, 2])